name: setup-g3ops
description: Install G3Ops
author: John Brunton
branding:
  color: green
  icon: play
inputs:
  token:
    description: "Github token to use to avoid rate limits"
    required: false
    default: ""
  version:
    description: "The version of G3Ops to install (default: latest)"
    required: false
    default: latest
runs:
  using: 'node12'
  main: 'dist/index.js'
