name: sandbox

build:
  env:
    COMPOSE_FILE: docker-compose.yml
    TAG: $BUILD_VERSION-$BUILD_ID

  command: |
    echo "$G3OPS_DOCKER_ACCESS_TOKEN" | docker login -u "$G3OPS_DOCKER_USERNAME" --password-stdin
    docker-compose build
    docker-compose push
    docker-compose config | kbld --images-annotation=false -f - | ytt -f - -f config/clean-contexts.yml > config/docker-compose.yml

  commit:
    message: "Build $BUILD_VERSION"
    files: [config/docker-compose.yml]
    branch: develop

  package:
    image: jbrunton/g3ops-sandbox-config:$BUILD_VERSION
    files: [config/docker-compose.yml]

deploy:
  command: |
    echo "Deploying $BUILD_VERSION to $ENVIRONMENT ..."
    cat config/docker-compose.yml
